# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mount_Piezo_Wafer-1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1042, 802)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 801))
        self.label.setStyleSheet("background-image: url(:/newPrefix/Mount Piezo Wafer - 1.PNG);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Mount Piezo Wafer - 1.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_Data = QtWidgets.QLineEdit(Form)
        self.lineEdit_Data.setEnabled(True)
        self.lineEdit_Data.setGeometry(QtCore.QRect(680, 160, 113, 22))
        self.lineEdit_Data.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_Data.setText("")
        self.lineEdit_Data.setMaxLength(32767)
        self.lineEdit_Data.setObjectName("lineEdit_Data")
        self.textEdit_Comments = QtWidgets.QTextEdit(Form)
        self.textEdit_Comments.setGeometry(QtCore.QRect(330, 210, 581, 191))
        self.textEdit_Comments.setObjectName("textEdit_Comments")
        self.pushButton_buttom = QtWidgets.QPushButton(Form)
        self.pushButton_buttom.setGeometry(QtCore.QRect(920, 750, 93, 28))
        self.pushButton_buttom.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.pushButton_buttom.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_buttom.setAutoDefault(False)
        self.pushButton_buttom.setObjectName("pushButton_buttom")
        self.lineEdit_Steps = QtWidgets.QLineEdit(Form)
        self.lineEdit_Steps.setGeometry(QtCore.QRect(120, 750, 91, 22))
        self.lineEdit_Steps.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"\n"
"}")
        self.lineEdit_Steps.setObjectName("lineEdit_Steps")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(220, 750, 71, 22))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_buttom_2 = QtWidgets.QPushButton(Form)
        self.pushButton_buttom_2.setGeometry(QtCore.QRect(810, 750, 93, 28))
        self.pushButton_buttom_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.pushButton_buttom_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_buttom_2.setAutoDefault(False)
        self.pushButton_buttom_2.setObjectName("pushButton_buttom_2")
        self.pushButton_buttom_3 = QtWidgets.QPushButton(Form)
        self.pushButton_buttom_3.setGeometry(QtCore.QRect(690, 750, 93, 28))
        self.pushButton_buttom_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.pushButton_buttom_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_buttom_3.setAutoDefault(False)
        self.pushButton_buttom_3.setObjectName("pushButton_buttom_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_Data.setPlaceholderText(_translate("Form", "      Initial Here"))
        self.textEdit_Comments.setPlaceholderText(_translate("Form", "Please provide detailed descriptions if you feel necessary"))
        self.pushButton_buttom.setText(_translate("Form", "Next"))
        self.pushButton_buttom_2.setText(_translate("Form", "Previous"))
        self.pushButton_buttom_3.setText(_translate("Form", "Back"))
        
import wafer_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
    MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())