# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Adminstrator_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Administrator_window(object):
    def setupUi(self, Administrator_window):
        Administrator_window.setObjectName("Administrator_window")
        Administrator_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Administrator_window)
        self.centralwidget.setObjectName("centralwidget")
        self.login_content = QtWidgets.QFrame(self.centralwidget)
        self.login_content.setGeometry(QtCore.QRect(90, 20, 657, 516))
        self.login_content.setStyleSheet("QFrame {\n"
"    border-image: url(:/images/images/Daxsonics-Logo-Padded.png);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.login_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_content.setObjectName("login_content")
        self.pushButton_3 = QtWidgets.QPushButton(self.login_content)
        self.pushButton_3.setGeometry(QtCore.QRect(599, 10, 42, 20))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Close-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.login_content)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 10, 43, 20))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Minus-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        Administrator_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Administrator_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Administrator_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Administrator_window)
        self.statusbar.setObjectName("statusbar")
        Administrator_window.setStatusBar(self.statusbar)

        self.retranslateUi(Administrator_window)
        QtCore.QMetaObject.connectSlotsByName(Administrator_window)

    def retranslateUi(self, Administrator_window):
        _translate = QtCore.QCoreApplication.translate
        Administrator_window.setWindowTitle(_translate("Administrator_window", "MainWindow"))
import resource_rc
