# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Window(object):
    def setupUi(self, Admin_Window):
        Admin_Window.setObjectName("Admin_Window")
        Admin_Window.resize(1024, 600)
        Admin_Window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(Admin_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Product_System_UI = QtWidgets.QWidget()
        self.Product_System_UI.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0.0284091 rgb(240, 240, 240), stop:0.9375 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 14;\n"
"}\n"
"\n"
"QGroupBox {\n"
"border: 2px solid #999999;\n"
"border-radius: 4px;\n"
"margin-top: 0.5em;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top left;\n"
"left: 1em;\n"
"top: 0.1em;\n"
"}")
        self.Product_System_UI.setObjectName("Product_System_UI")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Product_System_UI)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(self.Product_System_UI)
        self.widget.setMinimumSize(QtCore.QSize(950, 550))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.workflow_database_system = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.workflow_database_system.setFont(font)
        self.workflow_database_system.setObjectName("workflow_database_system")
        self.horizontalLayout_5.addWidget(self.workflow_database_system)
        spacerItem = QtWidgets.QSpacerItem(80, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.barcode_number = QtWidgets.QLineEdit(self.widget)
        self.barcode_number.setObjectName("barcode_number")
        self.horizontalLayout_5.addWidget(self.barcode_number)
        self.pushButton_enter = QtWidgets.QPushButton(self.widget)
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.horizontalLayout_5.addWidget(self.pushButton_enter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pushButton_refresh_workflow = QtWidgets.QPushButton(self.widget)
        self.pushButton_refresh_workflow.setObjectName("pushButton_refresh_workflow")
        self.horizontalLayout_5.addWidget(self.pushButton_refresh_workflow)
        self.pushButton_close_workflow = QtWidgets.QPushButton(self.widget)
        self.pushButton_close_workflow.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    height: 35px;\n"
"background-image:None;\n"
"border-color:None;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.pushButton_close_workflow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close_button.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_workflow.setIcon(icon)
        self.pushButton_close_workflow.setObjectName("pushButton_close_workflow")
        self.horizontalLayout_5.addWidget(self.pushButton_close_workflow)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 3000, 3000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setMinimumSize(QtCore.QSize(3000, 3000))
        self.frame_2.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableView_workflow = QtWidgets.QTableView(self.frame_2)
        self.tableView_workflow.setObjectName("tableView_workflow")
        self.verticalLayout_7.addWidget(self.tableView_workflow)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addWidget(self.widget)
        self.stackedWidget.addWidget(self.Product_System_UI)
        self.User_System_UI = QtWidgets.QWidget()
        self.User_System_UI.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0.0284091 rgb(240, 240, 240), stop:0.9375 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 14;\n"
"}\n"
"\n"
"QGroupBox {\n"
"border: 2px solid #999999;\n"
"border-radius: 4px;\n"
"margin-top: 0.5em;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top left;\n"
"left: 1em;\n"
"top: 0.1em;\n"
"}")
        self.User_System_UI.setObjectName("User_System_UI")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.User_System_UI)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.User_System_UI)
        self.widget_2.setMinimumSize(QtCore.QSize(950, 550))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.user_database_system = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.user_database_system.setFont(font)
        self.user_database_system.setObjectName("user_database_system")
        self.horizontalLayout_11.addWidget(self.user_database_system)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.fresh_pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.fresh_pushButton_2.setMinimumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.fresh_pushButton_2.setFont(font)
        self.fresh_pushButton_2.setObjectName("fresh_pushButton_2")
        self.horizontalLayout_11.addWidget(self.fresh_pushButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.pushButton_close_employee = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_close_employee.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    height: 35px;\n"
"    background-image:None;\n"
"    border-color:None;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.pushButton_close_employee.setText("")
        self.pushButton_close_employee.setIcon(icon)
        self.pushButton_close_employee.setObjectName("pushButton_close_employee")
        self.horizontalLayout_11.addWidget(self.pushButton_close_employee)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox_4.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.add_user_of_user_name_lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.add_user_of_user_name_lineEdit_2.setMinimumSize(QtCore.QSize(90, 30))
        self.add_user_of_user_name_lineEdit_2.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_user_of_user_name_lineEdit_2.setFont(font)
        self.add_user_of_user_name_lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.add_user_of_user_name_lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.add_user_of_user_name_lineEdit_2.setObjectName("add_user_of_user_name_lineEdit_2")
        self.verticalLayout_12.addWidget(self.add_user_of_user_name_lineEdit_2)
        self.add_useraccount = QtWidgets.QLineEdit(self.groupBox_4)
        self.add_useraccount.setMaximumSize(QtCore.QSize(120, 30))
        self.add_useraccount.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.add_useraccount.setObjectName("add_useraccount")
        self.verticalLayout_12.addWidget(self.add_useraccount)
        self.add_user_of_password_lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.add_user_of_password_lineEdit_2.setMinimumSize(QtCore.QSize(90, 30))
        self.add_user_of_password_lineEdit_2.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_user_of_password_lineEdit_2.setFont(font)
        self.add_user_of_password_lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.add_user_of_password_lineEdit_2.setObjectName("add_user_of_password_lineEdit_2")
        self.verticalLayout_12.addWidget(self.add_user_of_password_lineEdit_2)
        self.add_email = QtWidgets.QLineEdit(self.groupBox_4)
        self.add_email.setMaximumSize(QtCore.QSize(120, 30))
        self.add_email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.add_email.setObjectName("add_email")
        self.verticalLayout_12.addWidget(self.add_email)
        self.add_job = QtWidgets.QLineEdit(self.groupBox_4)
        self.add_job.setMaximumSize(QtCore.QSize(120, 30))
        self.add_job.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.add_job.setObjectName("add_job")
        self.verticalLayout_12.addWidget(self.add_job)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.add_user_pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.add_user_pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.add_user_pushButton_2.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.add_user_pushButton_2.setFont(font)
        self.add_user_pushButton_2.setObjectName("add_user_pushButton_2")
        self.horizontalLayout_13.addWidget(self.add_user_pushButton_2)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox_5.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_13.setSpacing(7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.disable_user_name = QtWidgets.QLineEdit(self.groupBox_5)
        self.disable_user_name.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.disable_user_name.setFont(font)
        self.disable_user_name.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.disable_user_name.setObjectName("disable_user_name")
        self.verticalLayout_13.addWidget(self.disable_user_name)
        self.disable_password = QtWidgets.QLineEdit(self.groupBox_5)
        self.disable_password.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.disable_password.setFont(font)
        self.disable_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:2px;")
        self.disable_password.setObjectName("disable_password")
        self.verticalLayout_13.addWidget(self.disable_password)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.disable_user_pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.disable_user_pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.disable_user_pushButton_2.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.disable_user_pushButton_2.setFont(font)
        self.disable_user_pushButton_2.setObjectName("disable_user_pushButton_2")
        self.verticalLayout_16.addWidget(self.disable_user_pushButton_2)
        self.enable_user_pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.enable_user_pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.enable_user_pushButton_2.setMaximumSize(QtCore.QSize(90, 30))
        self.enable_user_pushButton_2.setObjectName("enable_user_pushButton_2")
        self.verticalLayout_16.addWidget(self.enable_user_pushButton_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 3000, 3000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(3000, 3000))
        self.frame.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_employee = QtWidgets.QTableView(self.frame)
        self.tableView_employee.setObjectName("tableView_employee")
        self.verticalLayout_3.addWidget(self.tableView_employee)
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_12.addWidget(self.scrollArea)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.User_System_UI)
        self.horizontalLayout_15.addWidget(self.stackedWidget)
        Admin_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Admin_Window)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Admin_Window)

    def retranslateUi(self, Admin_Window):
        _translate = QtCore.QCoreApplication.translate
        Admin_Window.setWindowTitle(_translate("Admin_Window", "MainWindow"))
        self.workflow_database_system.setText(_translate("Admin_Window", "Workflow Database System"))
        self.barcode_number.setPlaceholderText(_translate("Admin_Window", "Barcode #"))
        self.pushButton_enter.setText(_translate("Admin_Window", "Enter"))
        self.pushButton_refresh_workflow.setText(_translate("Admin_Window", "Refresh"))
        self.user_database_system.setText(_translate("Admin_Window", "   User Database System"))
        self.fresh_pushButton_2.setText(_translate("Admin_Window", "The Information of Employees"))
        self.groupBox_4.setTitle(_translate("Admin_Window", "Add User"))
        self.add_user_of_user_name_lineEdit_2.setPlaceholderText(_translate("Admin_Window", "User Name"))
        self.add_useraccount.setPlaceholderText(_translate("Admin_Window", "User Account #"))
        self.add_user_of_password_lineEdit_2.setPlaceholderText(_translate("Admin_Window", "Password"))
        self.add_email.setPlaceholderText(_translate("Admin_Window", "Email"))
        self.add_job.setPlaceholderText(_translate("Admin_Window", "Job Title"))
        self.add_user_pushButton_2.setText(_translate("Admin_Window", "Add"))
        self.groupBox_5.setTitle(_translate("Admin_Window", "Disable User"))
        self.disable_user_name.setPlaceholderText(_translate("Admin_Window", "User Name"))
        self.disable_password.setPlaceholderText(_translate("Admin_Window", "Password"))
        self.disable_user_pushButton_2.setText(_translate("Admin_Window", "Disable"))
        self.enable_user_pushButton_2.setText(_translate("Admin_Window", "Enable"))
import resource_rc
