# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instruction_Window_presentation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstructionWindow(object):
    def setupUi(self, InstructionWindow):
        InstructionWindow.setObjectName("InstructionWindow")
        InstructionWindow.resize(1024, 600)
        InstructionWindow.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(InstructionWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMaximumSize(QtCore.QSize(1024, 600))
        self.stackedWidget.setStyleSheet("border-image: url(:/images/images/Mount_Piezo_Wafer_2.PNG);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setMaximumSize(QtCore.QSize(1024, 600))
        self.HomePage.setStyleSheet("border-image: url(:/images/images/WI_301610.png);")
        self.HomePage.setObjectName("HomePage")
        self.HomePage_Name = QtWidgets.QTextEdit(self.HomePage)
        self.HomePage_Name.setGeometry(QtCore.QRect(80, 360, 401, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomePage_Name.sizePolicy().hasHeightForWidth())
        self.HomePage_Name.setSizePolicy(sizePolicy)
        self.HomePage_Name.setStyleSheet("border-image:None;\n"
"")
        self.HomePage_Name.setObjectName("HomePage_Name")
        self.HomePage_Next = QtWidgets.QPushButton(self.HomePage)
        self.HomePage_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.HomePage_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.HomePage_Next.setObjectName("HomePage_Next")
        self.HomePage_Back = QtWidgets.QPushButton(self.HomePage)
        self.HomePage_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.HomePage_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.HomePage_Back.setObjectName("HomePage_Back")
        self.stackedWidget.addWidget(self.HomePage)
        self.Mount_Piezo_Wafer_1 = QtWidgets.QWidget()
        self.Mount_Piezo_Wafer_1.setMaximumSize(QtCore.QSize(1024, 600))
        self.Mount_Piezo_Wafer_1.setStyleSheet("border-image: url(:/images/images/Mount_Piezo_Wafer_1.PNG);")
        self.Mount_Piezo_Wafer_1.setObjectName("Mount_Piezo_Wafer_1")
        self.Mount_Piezo_Wafer_1_Comments_3 = QtWidgets.QTextEdit(self.Mount_Piezo_Wafer_1)
        self.Mount_Piezo_Wafer_1_Comments_3.setGeometry(QtCore.QRect(330, 160, 551, 141))
        self.Mount_Piezo_Wafer_1_Comments_3.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Piezo_Wafer_1_Comments_3.setObjectName("Mount_Piezo_Wafer_1_Comments_3")
        self.Mount_Piezo_Wafer_1_Next = QtWidgets.QPushButton(self.Mount_Piezo_Wafer_1)
        self.Mount_Piezo_Wafer_1_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.Mount_Piezo_Wafer_1_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Mount_Piezo_Wafer_1_Next.setIconSize(QtCore.QSize(20, 20))
        self.Mount_Piezo_Wafer_1_Next.setAutoDefault(False)
        self.Mount_Piezo_Wafer_1_Next.setObjectName("Mount_Piezo_Wafer_1_Next")
        self.Mount_Piezo_Wafer_1_Back = QtWidgets.QPushButton(self.Mount_Piezo_Wafer_1)
        self.Mount_Piezo_Wafer_1_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.Mount_Piezo_Wafer_1_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Mount_Piezo_Wafer_1_Back.setIconSize(QtCore.QSize(20, 20))
        self.Mount_Piezo_Wafer_1_Back.setAutoDefault(False)
        self.Mount_Piezo_Wafer_1_Back.setObjectName("Mount_Piezo_Wafer_1_Back")
        self.Mount_Piezo_Wafer_1_Initial = QtWidgets.QLineEdit(self.Mount_Piezo_Wafer_1)
        self.Mount_Piezo_Wafer_1_Initial.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.Mount_Piezo_Wafer_1_Initial.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Mount_Piezo_Wafer_1_Initial.setObjectName("Mount_Piezo_Wafer_1_Initial")
        self.Mount_Piezo_Wafer_1_Dates = QtWidgets.QLineEdit(self.Mount_Piezo_Wafer_1)
        self.Mount_Piezo_Wafer_1_Dates.setGeometry(QtCore.QRect(110, 560, 90, 22))
        self.Mount_Piezo_Wafer_1_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Mount_Piezo_Wafer_1_Dates.setObjectName("Mount_Piezo_Wafer_1_Dates")
        self.Mount_Piezo_Wafer_1_Data = QtWidgets.QLineEdit(self.Mount_Piezo_Wafer_1)
        self.Mount_Piezo_Wafer_1_Data.setEnabled(True)
        self.Mount_Piezo_Wafer_1_Data.setGeometry(QtCore.QRect(700, 110, 113, 22))
        self.Mount_Piezo_Wafer_1_Data.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Piezo_Wafer_1_Data.setText("")
        self.Mount_Piezo_Wafer_1_Data.setMaxLength(32767)
        self.Mount_Piezo_Wafer_1_Data.setAlignment(QtCore.Qt.AlignCenter)
        self.Mount_Piezo_Wafer_1_Data.setObjectName("Mount_Piezo_Wafer_1_Data")
        self.stackedWidget.addWidget(self.Mount_Piezo_Wafer_1)
        self.DicePiezoWaferintoSubwafers1 = QtWidgets.QWidget()
        self.DicePiezoWaferintoSubwafers1.setStyleSheet("border-image: url(:/images/images/subwafer1.PNG);")
        self.DicePiezoWaferintoSubwafers1.setObjectName("DicePiezoWaferintoSubwafers1")
        self.DicePiezoWaferintoSubwafers1_Data = QtWidgets.QLineEdit(self.DicePiezoWaferintoSubwafers1)
        self.DicePiezoWaferintoSubwafers1_Data.setEnabled(True)
        self.DicePiezoWaferintoSubwafers1_Data.setGeometry(QtCore.QRect(550, 120, 111, 21))
        self.DicePiezoWaferintoSubwafers1_Data.setStyleSheet("border-image:None;\n"
"border: None;")
        self.DicePiezoWaferintoSubwafers1_Data.setText("")
        self.DicePiezoWaferintoSubwafers1_Data.setMaxLength(32767)
        self.DicePiezoWaferintoSubwafers1_Data.setAlignment(QtCore.Qt.AlignCenter)
        self.DicePiezoWaferintoSubwafers1_Data.setObjectName("DicePiezoWaferintoSubwafers1_Data")
        self.DicePiezoWaferintoSubwafers1_Dates = QtWidgets.QLineEdit(self.DicePiezoWaferintoSubwafers1)
        self.DicePiezoWaferintoSubwafers1_Dates.setGeometry(QtCore.QRect(110, 560, 91, 22))
        self.DicePiezoWaferintoSubwafers1_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.DicePiezoWaferintoSubwafers1_Dates.setObjectName("DicePiezoWaferintoSubwafers1_Dates")
        self.DicePiezoWaferintoSubwafers1_Next = QtWidgets.QPushButton(self.DicePiezoWaferintoSubwafers1)
        self.DicePiezoWaferintoSubwafers1_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.DicePiezoWaferintoSubwafers1_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.DicePiezoWaferintoSubwafers1_Next.setIconSize(QtCore.QSize(20, 20))
        self.DicePiezoWaferintoSubwafers1_Next.setAutoDefault(False)
        self.DicePiezoWaferintoSubwafers1_Next.setObjectName("DicePiezoWaferintoSubwafers1_Next")
        self.DicePiezoWaferintoSubwafers1_Initals = QtWidgets.QLineEdit(self.DicePiezoWaferintoSubwafers1)
        self.DicePiezoWaferintoSubwafers1_Initals.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.DicePiezoWaferintoSubwafers1_Initals.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.DicePiezoWaferintoSubwafers1_Initals.setObjectName("DicePiezoWaferintoSubwafers1_Initals")
        self.DicePiezoWaferintoSubwafers1_Back = QtWidgets.QPushButton(self.DicePiezoWaferintoSubwafers1)
        self.DicePiezoWaferintoSubwafers1_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.DicePiezoWaferintoSubwafers1_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.DicePiezoWaferintoSubwafers1_Back.setIconSize(QtCore.QSize(20, 20))
        self.DicePiezoWaferintoSubwafers1_Back.setAutoDefault(False)
        self.DicePiezoWaferintoSubwafers1_Back.setObjectName("DicePiezoWaferintoSubwafers1_Back")
        self.DicePiezoWaferintoSubwafers1_comments = QtWidgets.QTextEdit(self.DicePiezoWaferintoSubwafers1)
        self.DicePiezoWaferintoSubwafers1_comments.setGeometry(QtCore.QRect(100, 160, 551, 111))
        self.DicePiezoWaferintoSubwafers1_comments.setStyleSheet("border-image:None;\n"
"border: None;")
        self.DicePiezoWaferintoSubwafers1_comments.setObjectName("DicePiezoWaferintoSubwafers1_comments")
        self.stackedWidget.addWidget(self.DicePiezoWaferintoSubwafers1)
        self.Dice_Framing_Piezo_3 = QtWidgets.QWidget()
        self.Dice_Framing_Piezo_3.setMaximumSize(QtCore.QSize(1024, 600))
        self.Dice_Framing_Piezo_3.setStyleSheet("border-image: url(:/images/images/Dice_Framing_Piezo_3.png);")
        self.Dice_Framing_Piezo_3.setObjectName("Dice_Framing_Piezo_3")
        self.Dice_Framing_Piezo_3_Comments = QtWidgets.QTextEdit(self.Dice_Framing_Piezo_3)
        self.Dice_Framing_Piezo_3_Comments.setGeometry(QtCore.QRect(50, 320, 641, 111))
        self.Dice_Framing_Piezo_3_Comments.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Dice_Framing_Piezo_3_Comments.setObjectName("Dice_Framing_Piezo_3_Comments")
        self.Dice_Framing_Piezo_3_Data = QtWidgets.QLineEdit(self.Dice_Framing_Piezo_3)
        self.Dice_Framing_Piezo_3_Data.setGeometry(QtCore.QRect(610, 180, 101, 22))
        self.Dice_Framing_Piezo_3_Data.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Dice_Framing_Piezo_3_Data.setAlignment(QtCore.Qt.AlignCenter)
        self.Dice_Framing_Piezo_3_Data.setReadOnly(False)
        self.Dice_Framing_Piezo_3_Data.setObjectName("Dice_Framing_Piezo_3_Data")
        self.Dice_Framing_Piezo_3_Next = QtWidgets.QPushButton(self.Dice_Framing_Piezo_3)
        self.Dice_Framing_Piezo_3_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.Dice_Framing_Piezo_3_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Dice_Framing_Piezo_3_Next.setObjectName("Dice_Framing_Piezo_3_Next")
        self.Dice_Framing_Piezo_3_Back = QtWidgets.QPushButton(self.Dice_Framing_Piezo_3)
        self.Dice_Framing_Piezo_3_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.Dice_Framing_Piezo_3_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Dice_Framing_Piezo_3_Back.setObjectName("Dice_Framing_Piezo_3_Back")
        self.Dice_Framing_Piezo_3_Initial = QtWidgets.QLineEdit(self.Dice_Framing_Piezo_3)
        self.Dice_Framing_Piezo_3_Initial.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.Dice_Framing_Piezo_3_Initial.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Dice_Framing_Piezo_3_Initial.setObjectName("Dice_Framing_Piezo_3_Initial")
        self.Dice_Framing_Piezo_3_Dates = QtWidgets.QLineEdit(self.Dice_Framing_Piezo_3)
        self.Dice_Framing_Piezo_3_Dates.setGeometry(QtCore.QRect(110, 560, 91, 22))
        self.Dice_Framing_Piezo_3_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Dice_Framing_Piezo_3_Dates.setObjectName("Dice_Framing_Piezo_3_Dates")
        self.stackedWidget.addWidget(self.Dice_Framing_Piezo_3)
        self.Premount_Clean_and_Measure_Subwafer_1 = QtWidgets.QWidget()
        self.Premount_Clean_and_Measure_Subwafer_1.setMaximumSize(QtCore.QSize(1024, 600))
        self.Premount_Clean_and_Measure_Subwafer_1.setStyleSheet("border-image: url(:/images/images/Premount_Clean_and_Measure_Subwafer_1.png);")
        self.Premount_Clean_and_Measure_Subwafer_1.setObjectName("Premount_Clean_and_Measure_Subwafer_1")
        self.Premount_Clean_and_Measure_Subwafer_1_Data0 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data0.setGeometry(QtCore.QRect(460, 170, 81, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data0.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data0.setAlignment(QtCore.Qt.AlignCenter)
        self.Premount_Clean_and_Measure_Subwafer_1_Data0.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data0")
        self.Premount_Clean_and_Measure_Subwafer_1_Data1 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data1.setGeometry(QtCore.QRect(650, 110, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data1.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data1.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data1")
        self.Premount_Clean_and_Measure_Subwafer_1_Data2 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data2.setGeometry(QtCore.QRect(590, 220, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data2.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data2.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data2")
        self.Premount_Clean_and_Measure_Subwafer_1_Data3 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data3.setGeometry(QtCore.QRect(610, 320, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data3.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data3.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data3")
        self.Premount_Clean_and_Measure_Subwafer_1_Data4 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data4.setGeometry(QtCore.QRect(850, 320, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data4.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data4.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data4")
        self.Premount_Clean_and_Measure_Subwafer_1_Data5 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data5.setGeometry(QtCore.QRect(880, 150, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data5.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data5.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data5")
        self.Premount_Clean_and_Measure_Subwafer_1_Data6 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data6.setGeometry(QtCore.QRect(780, 410, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data6.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data6.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data6")
        self.Premount_Clean_and_Measure_Subwafer_1_Data7 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data7.setGeometry(QtCore.QRect(780, 450, 71, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data7.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data7.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data7")
        self.Premount_Clean_and_Measure_Subwafer_1_Data8 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data8.setGeometry(QtCore.QRect(370, 420, 51, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data8.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data8.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data8")
        self.Premount_Clean_and_Measure_Subwafer_1_Data9 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data9.setGeometry(QtCore.QRect(380, 480, 51, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data9.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data9.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data9")
        self.Premount_Clean_and_Measure_Subwafer_1_Data10 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data10.setGeometry(QtCore.QRect(90, 440, 61, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data10.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data10.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data10")
        self.Premount_Clean_and_Measure_Subwafer_1_Data11 = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Data11.setGeometry(QtCore.QRect(110, 500, 61, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Data11.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Data11.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Data11")
        self.Premount_Clean_and_Measure_Subwafer_1_Initial = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Initial.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Initial.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Premount_Clean_and_Measure_Subwafer_1_Initial.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Initial")
        self.Premount_Clean_and_Measure_Subwafer_1_Dates = QtWidgets.QLineEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Dates.setGeometry(QtCore.QRect(110, 560, 91, 22))
        self.Premount_Clean_and_Measure_Subwafer_1_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Premount_Clean_and_Measure_Subwafer_1_Dates.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Dates")
        self.Premount_Clean_and_Measure_Subwafer_1_Next = QtWidgets.QPushButton(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.Premount_Clean_and_Measure_Subwafer_1_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Premount_Clean_and_Measure_Subwafer_1_Next.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Next")
        self.Premount_Clean_and_Measure_Subwafer_1_Back = QtWidgets.QPushButton(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.Premount_Clean_and_Measure_Subwafer_1_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Premount_Clean_and_Measure_Subwafer_1_Back.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Back")
        self.Premount_Clean_and_Measure_Subwafer_1_Comments = QtWidgets.QTextEdit(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Premount_Clean_and_Measure_Subwafer_1_Comments.setGeometry(QtCore.QRect(20, 280, 521, 101))
        self.Premount_Clean_and_Measure_Subwafer_1_Comments.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Premount_Clean_and_Measure_Subwafer_1_Comments.setObjectName("Premount_Clean_and_Measure_Subwafer_1_Comments")
        self.stackedWidget.addWidget(self.Premount_Clean_and_Measure_Subwafer_1)
        self.Mount_Subwafers = QtWidgets.QWidget()
        self.Mount_Subwafers.setMaximumSize(QtCore.QSize(1024, 600))
        self.Mount_Subwafers.setStyleSheet("border-image: url(:/images/images/Mount_Subwafers.png);")
        self.Mount_Subwafers.setObjectName("Mount_Subwafers")
        self.Mount_Subwafers_Comments = QtWidgets.QTextEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Comments.setGeometry(QtCore.QRect(580, 480, 411, 81))
        self.Mount_Subwafers_Comments.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Comments.setObjectName("Mount_Subwafers_Comments")
        self.Mount_Subwafers_Data1 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data1.setGeometry(QtCore.QRect(910, 420, 71, 22))
        self.Mount_Subwafers_Data1.setStyleSheet("border-image:None;")
        self.Mount_Subwafers_Data1.setObjectName("Mount_Subwafers_Data1")
        self.Mount_Subwafers_Data2_Special = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data2_Special.setGeometry(QtCore.QRect(820, 420, 71, 22))
        self.Mount_Subwafers_Data2_Special.setStyleSheet("border-image:None;")
        self.Mount_Subwafers_Data2_Special.setObjectName("Mount_Subwafers_Data2_Special")
        self.Mount_Subwafers_Data3 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data3.setGeometry(QtCore.QRect(720, 420, 71, 22))
        self.Mount_Subwafers_Data3.setStyleSheet("border-image:None;")
        self.Mount_Subwafers_Data3.setObjectName("Mount_Subwafers_Data3")
        self.Mount_Subwafers_Data4 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data4.setGeometry(QtCore.QRect(720, 380, 71, 22))
        self.Mount_Subwafers_Data4.setStyleSheet("border-image:None;")
        self.Mount_Subwafers_Data4.setObjectName("Mount_Subwafers_Data4")
        self.Mount_Subwafers_Data5_Special = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data5_Special.setGeometry(QtCore.QRect(820, 380, 71, 22))
        self.Mount_Subwafers_Data5_Special.setStyleSheet("border-image:None;")
        self.Mount_Subwafers_Data5_Special.setObjectName("Mount_Subwafers_Data5_Special")
        self.Mount_Subwafers_Data6 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data6.setGeometry(QtCore.QRect(910, 380, 71, 22))
        self.Mount_Subwafers_Data6.setStyleSheet("border-image:None;")
        self.Mount_Subwafers_Data6.setObjectName("Mount_Subwafers_Data6")
        self.Mount_Subwafers_Data7 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data7.setGeometry(QtCore.QRect(920, 240, 71, 22))
        self.Mount_Subwafers_Data7.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data7.setObjectName("Mount_Subwafers_Data7")
        self.Mount_Subwafers_Data8 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data8.setGeometry(QtCore.QRect(920, 50, 71, 22))
        self.Mount_Subwafers_Data8.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data8.setObjectName("Mount_Subwafers_Data8")
        self.Mount_Subwafers_Data9 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data9.setGeometry(QtCore.QRect(620, 20, 71, 22))
        self.Mount_Subwafers_Data9.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data9.setObjectName("Mount_Subwafers_Data9")
        self.Mount_Subwafers_Data10 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data10.setGeometry(QtCore.QRect(560, 110, 71, 22))
        self.Mount_Subwafers_Data10.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data10.setObjectName("Mount_Subwafers_Data10")
        self.Mount_Subwafers_Data11 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data11.setGeometry(QtCore.QRect(580, 220, 71, 22))
        self.Mount_Subwafers_Data11.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data11.setObjectName("Mount_Subwafers_Data11")
        self.Mount_Subwafers_Data12 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data12.setGeometry(QtCore.QRect(360, 420, 61, 22))
        self.Mount_Subwafers_Data12.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data12.setObjectName("Mount_Subwafers_Data12")
        self.Mount_Subwafers_Data13 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data13.setGeometry(QtCore.QRect(370, 480, 61, 22))
        self.Mount_Subwafers_Data13.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data13.setObjectName("Mount_Subwafers_Data13")
        self.Mount_Subwafers_Data14 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data14.setGeometry(QtCore.QRect(100, 500, 71, 22))
        self.Mount_Subwafers_Data14.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data14.setObjectName("Mount_Subwafers_Data14")
        self.Mount_Subwafers_Data15 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data15.setGeometry(QtCore.QRect(80, 440, 71, 22))
        self.Mount_Subwafers_Data15.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data15.setObjectName("Mount_Subwafers_Data15")
        self.Mount_Subwafers_Next = QtWidgets.QPushButton(self.Mount_Subwafers)
        self.Mount_Subwafers_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.Mount_Subwafers_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Mount_Subwafers_Next.setObjectName("Mount_Subwafers_Next")
        self.Mount_Subwafers_Back = QtWidgets.QPushButton(self.Mount_Subwafers)
        self.Mount_Subwafers_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.Mount_Subwafers_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Mount_Subwafers_Back.setObjectName("Mount_Subwafers_Back")
        self.Mount_Subwafers_Initial = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Initial.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.Mount_Subwafers_Initial.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Mount_Subwafers_Initial.setObjectName("Mount_Subwafers_Initial")
        self.Mount_Subwafers_Dates = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Dates.setGeometry(QtCore.QRect(110, 560, 91, 22))
        self.Mount_Subwafers_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Mount_Subwafers_Dates.setObjectName("Mount_Subwafers_Dates")
        self.Mount_Subwafers_Data0 = QtWidgets.QLineEdit(self.Mount_Subwafers)
        self.Mount_Subwafers_Data0.setGeometry(QtCore.QRect(470, 240, 81, 22))
        self.Mount_Subwafers_Data0.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Mount_Subwafers_Data0.setAlignment(QtCore.Qt.AlignCenter)
        self.Mount_Subwafers_Data0.setObjectName("Mount_Subwafers_Data0")
        self.stackedWidget.addWidget(self.Mount_Subwafers)
        self.Dice_First_Pillars_2 = QtWidgets.QWidget()
        self.Dice_First_Pillars_2.setMaximumSize(QtCore.QSize(1024, 600))
        self.Dice_First_Pillars_2.setStyleSheet("border-image: url(:/images/images/Dice_First_Pillars_2.png);")
        self.Dice_First_Pillars_2.setObjectName("Dice_First_Pillars_2")
        self.Dice_First_Pillars_2_Data = QtWidgets.QLineEdit(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Data.setGeometry(QtCore.QRect(500, 130, 71, 22))
        self.Dice_First_Pillars_2_Data.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Dice_First_Pillars_2_Data.setObjectName("Dice_First_Pillars_2_Data")
        self.Dice_First_Pillars_2_Initial1 = QtWidgets.QLineEdit(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Initial1.setGeometry(QtCore.QRect(500, 250, 91, 22))
        self.Dice_First_Pillars_2_Initial1.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Dice_First_Pillars_2_Initial1.setAlignment(QtCore.Qt.AlignCenter)
        self.Dice_First_Pillars_2_Initial1.setObjectName("Dice_First_Pillars_2_Initial1")
        self.Dice_First_Pillars_2_Dates = QtWidgets.QLineEdit(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Dates.setGeometry(QtCore.QRect(110, 560, 91, 22))
        self.Dice_First_Pillars_2_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Dice_First_Pillars_2_Dates.setObjectName("Dice_First_Pillars_2_Dates")
        self.Dice_First_Pillars_2_Initial2 = QtWidgets.QLineEdit(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Initial2.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.Dice_First_Pillars_2_Initial2.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.Dice_First_Pillars_2_Initial2.setObjectName("Dice_First_Pillars_2_Initial2")
        self.Dice_First_Pillars_2_Comments = QtWidgets.QTextEdit(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Comments.setGeometry(QtCore.QRect(40, 380, 551, 111))
        self.Dice_First_Pillars_2_Comments.setStyleSheet("border-image:None;\n"
"border: None;")
        self.Dice_First_Pillars_2_Comments.setObjectName("Dice_First_Pillars_2_Comments")
        self.Dice_First_Pillars_2_Next = QtWidgets.QPushButton(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.Dice_First_Pillars_2_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Dice_First_Pillars_2_Next.setObjectName("Dice_First_Pillars_2_Next")
        self.Dice_First_Pillars_2_Back = QtWidgets.QPushButton(self.Dice_First_Pillars_2)
        self.Dice_First_Pillars_2_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.Dice_First_Pillars_2_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.Dice_First_Pillars_2_Back.setObjectName("Dice_First_Pillars_2_Back")
        self.stackedWidget.addWidget(self.Dice_First_Pillars_2)
        self.LapSecondEpoxyFill = QtWidgets.QWidget()
        self.LapSecondEpoxyFill.setStyleSheet("border-image: url(:/images/images/LapSecondEpoxyFill.PNG);")
        self.LapSecondEpoxyFill.setObjectName("LapSecondEpoxyFill")
        self.LapSecondEpoxyFill_Data1 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data1.setGeometry(QtCore.QRect(600, 96, 71, 20))
        self.LapSecondEpoxyFill_Data1.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data1.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data1.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data1.setObjectName("LapSecondEpoxyFill_Data1")
        self.LapSecondEpoxyFill_Data2 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data2.setGeometry(QtCore.QRect(910, 130, 71, 20))
        self.LapSecondEpoxyFill_Data2.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data2.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data2.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data2.setObjectName("LapSecondEpoxyFill_Data2")
        self.LapSecondEpoxyFill_Data3 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data3.setGeometry(QtCore.QRect(910, 316, 71, 20))
        self.LapSecondEpoxyFill_Data3.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data3.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data3.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data3.setObjectName("LapSecondEpoxyFill_Data3")
        self.LapSecondEpoxyFill_Data4 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data4.setGeometry(QtCore.QRect(570, 300, 71, 20))
        self.LapSecondEpoxyFill_Data4.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data4.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data4.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data4.setObjectName("LapSecondEpoxyFill_Data4")
        self.LapSecondEpoxyFill_Data5 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data5.setGeometry(QtCore.QRect(550, 196, 71, 20))
        self.LapSecondEpoxyFill_Data5.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data5.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data5.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data5.setObjectName("LapSecondEpoxyFill_Data5")
        self.LapSecondEpoxyFill_Data6 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data6.setGeometry(QtCore.QRect(220, 230, 45, 15))
        self.LapSecondEpoxyFill_Data6.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data6.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data6.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data6.setObjectName("LapSecondEpoxyFill_Data6")
        self.LapSecondEpoxyFill_Data7 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data7.setGeometry(QtCore.QRect(400, 230, 45, 15))
        self.LapSecondEpoxyFill_Data7.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data7.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data7.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data7.setObjectName("LapSecondEpoxyFill_Data7")
        self.LapSecondEpoxyFill_Data8 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data8.setGeometry(QtCore.QRect(230, 410, 45, 15))
        self.LapSecondEpoxyFill_Data8.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data8.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data8.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data8.setObjectName("LapSecondEpoxyFill_Data8")
        self.LapSecondEpoxyFill_Data9 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data9.setGeometry(QtCore.QRect(390, 410, 45, 15))
        self.LapSecondEpoxyFill_Data9.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data9.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data9.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data9.setObjectName("LapSecondEpoxyFill_Data9")
        self.LapSecondEpoxyFill_Back = QtWidgets.QPushButton(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Back.setGeometry(QtCore.QRect(770, 570, 100, 30))
        self.LapSecondEpoxyFill_Back.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.LapSecondEpoxyFill_Back.setObjectName("LapSecondEpoxyFill_Back")
        self.LapSecondEpoxyFill_Dates = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Dates.setGeometry(QtCore.QRect(110, 560, 91, 22))
        self.LapSecondEpoxyFill_Dates.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.LapSecondEpoxyFill_Dates.setObjectName("LapSecondEpoxyFill_Dates")
        self.LapSecondEpoxyFill_Initials = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Initials.setGeometry(QtCore.QRect(210, 560, 81, 22))
        self.LapSecondEpoxyFill_Initials.setStyleSheet("QLineEdit{\n"
"background-color: rgb(240, 240, 240);\n"
"border: none;\n"
"border-image:None;\n"
"}")
        self.LapSecondEpoxyFill_Initials.setObjectName("LapSecondEpoxyFill_Initials")
        self.LapSecondEpoxyFill_Next = QtWidgets.QPushButton(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Next.setGeometry(QtCore.QRect(890, 570, 100, 30))
        self.LapSecondEpoxyFill_Next.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"height: 35px;\n"
"border-image:None;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-top:7px;\n"
"}")
        self.LapSecondEpoxyFill_Next.setObjectName("LapSecondEpoxyFill_Next")
        self.LapSecondEpoxyFill_Data10 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data10.setGeometry(QtCore.QRect(620, 400, 71, 20))
        self.LapSecondEpoxyFill_Data10.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data10.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data10.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data10.setObjectName("LapSecondEpoxyFill_Data10")
        self.LapSecondEpoxyFill_Data11 = QtWidgets.QLineEdit(self.LapSecondEpoxyFill)
        self.LapSecondEpoxyFill_Data11.setGeometry(QtCore.QRect(620, 440, 71, 20))
        self.LapSecondEpoxyFill_Data11.setToolTipDuration(-2)
        self.LapSecondEpoxyFill_Data11.setStyleSheet("border-image:None;\n"
"border: None;")
        self.LapSecondEpoxyFill_Data11.setAlignment(QtCore.Qt.AlignCenter)
        self.LapSecondEpoxyFill_Data11.setObjectName("LapSecondEpoxyFill_Data11")
        self.stackedWidget.addWidget(self.LapSecondEpoxyFill)
        self.verticalLayout.addWidget(self.stackedWidget)
        InstructionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InstructionWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(InstructionWindow)

    def retranslateUi(self, InstructionWindow):
        _translate = QtCore.QCoreApplication.translate
        InstructionWindow.setWindowTitle(_translate("InstructionWindow", "MainWindow"))
        self.HomePage_Next.setText(_translate("InstructionWindow", "Next"))
        self.HomePage_Back.setText(_translate("InstructionWindow", "Exit"))
        self.Mount_Piezo_Wafer_1_Comments_3.setPlaceholderText(_translate("InstructionWindow", "Please provide detailed descriptions if you feel necessary"))
        self.Mount_Piezo_Wafer_1_Next.setText(_translate("InstructionWindow", "Next"))
        self.Mount_Piezo_Wafer_1_Back.setText(_translate("InstructionWindow", "Exit"))
        self.Mount_Piezo_Wafer_1_Data.setPlaceholderText(_translate("InstructionWindow", "Initial Here"))
        self.DicePiezoWaferintoSubwafers1_Data.setPlaceholderText(_translate("InstructionWindow", "Initial Here"))
        self.DicePiezoWaferintoSubwafers1_Next.setText(_translate("InstructionWindow", "Next"))
        self.DicePiezoWaferintoSubwafers1_Back.setText(_translate("InstructionWindow", "Exit"))
        self.DicePiezoWaferintoSubwafers1_comments.setPlaceholderText(_translate("InstructionWindow", "Please provide detailed descriptions if you feel necessary"))
        self.Dice_Framing_Piezo_3_Comments.setPlaceholderText(_translate("InstructionWindow", "Please provide detailed descriptions if you feel necessary "))
        self.Dice_Framing_Piezo_3_Data.setPlaceholderText(_translate("InstructionWindow", "Initial Here"))
        self.Dice_Framing_Piezo_3_Next.setText(_translate("InstructionWindow", "Next"))
        self.Dice_Framing_Piezo_3_Back.setText(_translate("InstructionWindow", "Exit"))
        self.Premount_Clean_and_Measure_Subwafer_1_Data0.setPlaceholderText(_translate("InstructionWindow", "Initial Here"))
        self.Premount_Clean_and_Measure_Subwafer_1_Next.setText(_translate("InstructionWindow", "Next"))
        self.Premount_Clean_and_Measure_Subwafer_1_Back.setText(_translate("InstructionWindow", "Exit"))
        self.Premount_Clean_and_Measure_Subwafer_1_Comments.setPlaceholderText(_translate("InstructionWindow", "Please provide detailed descriptions if you feel necessary "))
        self.Mount_Subwafers_Comments.setPlaceholderText(_translate("InstructionWindow", "Please provide detailed descriptions if you feel necessary "))
        self.Mount_Subwafers_Next.setText(_translate("InstructionWindow", "Next"))
        self.Mount_Subwafers_Back.setText(_translate("InstructionWindow", "Exit"))
        self.Mount_Subwafers_Data0.setPlaceholderText(_translate("InstructionWindow", "Initial Here"))
        self.Dice_First_Pillars_2_Initial1.setPlaceholderText(_translate("InstructionWindow", "Initial Here"))
        self.Dice_First_Pillars_2_Comments.setPlaceholderText(_translate("InstructionWindow", "Please provide detailed descriptions if you feel necessary "))
        self.Dice_First_Pillars_2_Next.setText(_translate("InstructionWindow", "Next"))
        self.Dice_First_Pillars_2_Back.setText(_translate("InstructionWindow", "Exit"))
        self.LapSecondEpoxyFill_Back.setText(_translate("InstructionWindow", "Exit"))
        self.LapSecondEpoxyFill_Next.setText(_translate("InstructionWindow", "Finish"))
import resource_rc
