# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Employee_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Employee(object):
    def setupUi(self, Employee):
        Employee.setObjectName("Employee")
        Employee.resize(1024, 600)
        Employee.setMaximumSize(QtCore.QSize(1024, 600))
        self.employee_barcode = QtWidgets.QLineEdit(Employee)
        self.employee_barcode.setGeometry(QtCore.QRect(350, 250, 200, 30))
        self.employee_barcode.setMinimumSize(QtCore.QSize(0, 0))
        self.employee_barcode.setObjectName("employee_barcode")
        self.employee_continue = QtWidgets.QPushButton(Employee)
        self.employee_continue.setGeometry(QtCore.QRect(600, 250, 100, 30))
        self.employee_continue.setObjectName("employee_continue")
        self.employee_workstation = QtWidgets.QLabel(Employee)
        self.employee_workstation.setGeometry(QtCore.QRect(410, 70, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.employee_workstation.setFont(font)
        self.employee_workstation.setObjectName("employee_workstation")
        self.employee_close = QtWidgets.QPushButton(Employee)
        self.employee_close.setGeometry(QtCore.QRect(960, 28, 20, 20))
        self.employee_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    height: 35px;\n"
"background-image:None;\n"
"border-color:None;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.employee_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close_button.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.employee_close.setIcon(icon)
        self.employee_close.setObjectName("employee_close")

        self.retranslateUi(Employee)
        QtCore.QMetaObject.connectSlotsByName(Employee)

    def retranslateUi(self, Employee):
        _translate = QtCore.QCoreApplication.translate
        Employee.setWindowTitle(_translate("Employee", "Form"))
        self.employee_barcode.setPlaceholderText(_translate("Employee", "Barcode #"))
        self.employee_continue.setText(_translate("Employee", "Continue"))
        self.employee_workstation.setText(_translate("Employee", "Work Selection"))
import resource_rc
