# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI_Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(1024, 600)
        Login_Window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(Login_Window)
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_menu = QtWidgets.QFrame(self.centralwidget)
        self.login_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.login_menu.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.login_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_menu.setObjectName("login_menu")
        self.Titl_welcome = QtWidgets.QLabel(self.login_menu)
        self.Titl_welcome.setGeometry(QtCore.QRect(17, 70, 261, 29))
        self.Titl_welcome.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Titl_welcome.setFont(font)
        self.Titl_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.Titl_welcome.setObjectName("Titl_welcome")
        self.Password = QtWidgets.QLineEdit(self.login_menu)
        self.Password.setGeometry(QtCore.QRect(40, 270, 221, 70))
        self.Password.setMaximumSize(QtCore.QSize(260, 70))
        self.Password.setStyleSheet("QLineEdit {\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(0,0,0,100);\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Login_Button = QtWidgets.QPushButton(self.login_menu)
        self.Login_Button.setGeometry(QtCore.QRect(90, 400, 121, 51))
        self.Login_Button.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Login_Button.setFont(font)
        self.Login_Button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Login_Button.setObjectName("Login_Button")
        self.UserID = QtWidgets.QLineEdit(self.login_menu)
        self.UserID.setGeometry(QtCore.QRect(40, 150, 221, 61))
        self.UserID.setMaximumSize(QtCore.QSize(260, 70))
        self.UserID.setStyleSheet("QLineEdit {\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(0,0,0,100);\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.UserID.setText("")
        self.UserID.setObjectName("UserID")
        self.horizontalLayout_2.addWidget(self.login_menu)
        self.login_content = QtWidgets.QFrame(self.centralwidget)
        self.login_content.setStyleSheet("QFrame {\n"
"    border-image: url(:/images/images/Logo-Padded.png);\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.login_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_content.setObjectName("login_content")
        self.layoutWidget = QtWidgets.QWidget(self.login_content)
        self.layoutWidget.setGeometry(QtCore.QRect(610, 20, 62, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Minus-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Close-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addWidget(self.login_content)
        Login_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_Window)
        self.pushButton_2.clicked.connect(Login_Window.showMinimized) # type: ignore
        self.pushButton_3.clicked.connect(Login_Window.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "MainWindow"))
        self.Titl_welcome.setText(_translate("Login_Window", "Welcome to Login"))
        self.Password.setPlaceholderText(_translate("Login_Window", "Password:"))
        self.Login_Button.setText(_translate("Login_Window", "Login"))
        self.UserID.setPlaceholderText(_translate("Login_Window", "Employee ID:"))
import resource_rc
